-- create database if not exist mobile;
use mobile;

CREATE TABLE T_MOBILE_ARRIVAL
		(
			ID BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	 		IMEI VARCHAR(255),
	 		IMSI VARCHAR(255),
	 		ARRIVAL_TIME DATETIME,
	 		UPLOAD_TIME DATETIME,
	 		SIM_OPERATOR VARCHAR(255),
	 		PHONE_NUM VARCHAR(25),
	 		KIND VARCHAR(25),
			EXTEND_PROP1 VARCHAR(255),
			EXTEND_PROP2 VARCHAR(255),
			CREATOR_ID BIGINT(20),
	 		CREATOR VARCHAR(255),
			CREATED_TIME DATETIME,
			LAST_OPERATOR_ID BIGINT(20),
	 		LAST_OPERATOR VARCHAR(255),
			LAST_OPERATED_TIME DATETIME
		)ENGINE=INNODB  DEFAULT CHARSET=UTF8 DEFAULT COLLATE=UTF8_BIN;
		
CREATE TABLE T_MOBILE_BASIC_INFO
		(
			ID BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	 		PRODUCTION_ID VARCHAR(255),
	 		IMEI VARCHAR(255),
	 		MAC VARCHAR(255),
	 		IP VARCHAR(255),
	 		KERNEL VARCHAR(255),
	 		MODEL VARCHAR(255),
	 		IRELEASE VARCHAR(255),
	 		SDK VARCHAR(255),
	 		ROM VARCHAR(255),
	 		STORE_TIME DATETIME,
	 		UPLOAD_TIME DATETIME,
			EXTEND_PROP1 VARCHAR(255),
			EXTEND_PROP2 VARCHAR(255),
			CREATOR_ID BIGINT(20),
	 		CREATOR VARCHAR(255),
			CREATED_TIME DATETIME,
			LAST_OPERATOR_ID BIGINT(20),
	 		LAST_OPERATOR VARCHAR(255),
			LAST_OPERATED_TIME DATETIME
		)ENGINE=INNODB  DEFAULT CHARSET=UTF8 DEFAULT COLLATE=UTF8_BIN;
		
CREATE TABLE T_MOBILE_LOCATION
		(
			ID BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	 		IMEI VARCHAR(255),
	 		LONGITUDE DOUBLE,
	 		LATITUDE DOUBLE,
			LOCATION_TIME DATETIME,
			ADDRESS VARCHAR(1000),
			UPLOAD_TIME DATETIME,
			EXTEND_PROP1 VARCHAR(255),
			EXTEND_PROP2 VARCHAR(255),
			CREATOR_ID BIGINT(20),
	 		CREATOR VARCHAR(255),
			CREATED_TIME DATETIME,
			LAST_OPERATOR_ID BIGINT(20),
	 		LAST_OPERATOR VARCHAR(255),
			LAST_OPERATED_TIME DATETIME
		)ENGINE=INNODB  DEFAULT CHARSET=UTF8 DEFAULT COLLATE=UTF8_BIN;
		
CREATE TABLE T_MOBILE_DATA_USAGE
		(
			ID BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	 		IMEI VARCHAR(255),
	 		SIM_OPERATOR VARCHAR(255),
	 		G23_TIME BIGINT(20),
	 		G23_USAGE BIGINT(20),
	 		WIFI_TIME BIGINT(20),
	 		WIFI_USAGE BIGINT(20),
	 		STATISTICAL_TIME DATETIME,
	 		UPLOAD_TIME DATETIME,
			EXTEND_PROP1 VARCHAR(255),
			EXTEND_PROP2 VARCHAR(255),
			CREATOR_ID BIGINT(20),
	 		CREATOR VARCHAR(255),
			CREATED_TIME DATETIME,
			LAST_OPERATOR_ID BIGINT(20),
	 		LAST_OPERATOR VARCHAR(255),
			LAST_OPERATED_TIME DATETIME
		)ENGINE=INNODB  DEFAULT CHARSET=UTF8 DEFAULT COLLATE=UTF8_BIN;
		
CREATE TABLE T_MOBILE_ACTIVATED_INFO
		(
			ID BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	 		IMEI VARCHAR(255),
	 		APP_NAME VARCHAR(255),
	 		PACKAGE_NAME VARCHAR(255),
	 		ACTIVATED_TIME DATETIME,
	 		UPLOAD_TIME DATETIME,
			EXTEND_PROP1 VARCHAR(255),
			EXTEND_PROP2 VARCHAR(255),
			CREATOR_ID BIGINT(20),
	 		CREATOR VARCHAR(255),
			CREATED_TIME DATETIME,
			LAST_OPERATOR_ID BIGINT(20),
	 		LAST_OPERATOR VARCHAR(255),
			LAST_OPERATED_TIME DATETIME
		)ENGINE=INNODB  DEFAULT CHARSET=UTF8 DEFAULT COLLATE=UTF8_BIN;
		
CREATE TABLE T_MOBILE_APP_INSTALLED
		(
			ID BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
			IMEI VARCHAR(255),
	 		APP_NAME VARCHAR(255),
	 		PACKAGE_NAME VARCHAR(255),
	 		VERSION_NAME VARCHAR(255),
	 		VERSION_NO VARCHAR(255),
	 		INSTALLED_PATH VARCHAR(400),
	 		UPDATE_TIME DATETIME,
	 		UPLOAD_TIME DATETIME,
			EXTEND_PROP1 VARCHAR(255),
			EXTEND_PROP2 VARCHAR(255),
			CREATOR_ID BIGINT(20),
	 		CREATOR VARCHAR(255),
			CREATED_TIME DATETIME,
			LAST_OPERATOR_ID BIGINT(20),
	 		LAST_OPERATOR VARCHAR(255),
			LAST_OPERATED_TIME DATETIME
		)ENGINE=INNODB  DEFAULT CHARSET=UTF8 DEFAULT COLLATE=UTF8_BIN;
		
CREATE TABLE T_MOBILE_APP_MODIFY_INFO
		(
			ID BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	 		IMEI VARCHAR(255),
	 		APP_NAME VARCHAR(255),
	 		PACKAGE_NAME VARCHAR(255),
	 		VERSION_NAME VARCHAR(255),
	 		VERSION_NO VARCHAR(255),
	 		INSTALLED_PATH VARCHAR(400),
	 		MODIFY_TYPE INT,
	 		MODIFY_TIME DATETIME,
	 		UPLOAD_TIME DATETIME,
			EXTEND_PROP1 VARCHAR(255),
			EXTEND_PROP2 VARCHAR(255),
			CREATOR_ID BIGINT(20),
	 		CREATOR VARCHAR(255),
			CREATED_TIME DATETIME,
			LAST_OPERATOR_ID BIGINT(20),
	 		LAST_OPERATOR VARCHAR(255),
			LAST_OPERATED_TIME DATETIME
		)ENGINE=INNODB  DEFAULT CHARSET=UTF8 DEFAULT COLLATE=UTF8_BIN;

CREATE TABLE T_MOBILE_PUSH_MESSAGE
		(
			ID BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
			DEAL_TYPE VARCHAR(10),
	 		NOTI_TITLE VARCHAR(255),
	 		NOTI_CONTENT VARCHAR(500),
	 		NOTI_IMG_URL VARCHAR(255),
	 		OPEN_TYPE VARCHAR(10),
	 		NET_URL VARCHAR(400),
	 		NOTI_FILE_URL VARCHAR(500),
	 		PACKAGE_NAME VARCHAR(500),	
	 		EXTENDS_DATA1 VARCHAR(500),
	 		EXTENDS_DATA2 VARCHAR(500),
	 		EXTEND_PROP1 VARCHAR(255),
			EXTEND_PROP2 VARCHAR(255),
			CREATOR_ID BIGINT(20),
	 		CREATOR VARCHAR(255),
			CREATED_TIME DATETIME,
			LAST_OPERATOR_ID BIGINT(20),
	 		LAST_OPERATOR VARCHAR(255),
			LAST_OPERATED_TIME DATETIME
		)ENGINE=INNODB  DEFAULT CHARSET=UTF8 DEFAULT COLLATE=UTF8_BIN;

CREATE TABLE T_MOBILE_PUSH_MESSAGE_IMEI
		(
			ID BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	 		PUSH_MESSAGE_ID BIGINT(20),
	 		IMEI VARCHAR(255),
	 		MOBILE_LOCATION_ID BIGINT(20),
	 		PUSH_TIME DATETIME,
	 		PUSHED_COUNT INT,
	 		STATUS VARCHAR(255),
	 		EXTEND_PROP1 VARCHAR(255),
			EXTEND_PROP2 VARCHAR(255),
			CREATOR_ID BIGINT(20),
	 		CREATOR VARCHAR(255),
			CREATED_TIME DATETIME,
			LAST_OPERATOR_ID BIGINT(20),
	 		LAST_OPERATOR VARCHAR(255),
			LAST_OPERATED_TIME DATETIME,
			INDEX IDX_TMESSIMEI_IMEI(IMEI),
			INDEX IDX_TMESSIMEI_STUS(STATUS)			
		)ENGINE=INNODB  DEFAULT CHARSET=UTF8 DEFAULT COLLATE=UTF8_BIN;
		
CREATE TABLE T_MOBILE_IMEI_USER
		(
			ID BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	 		IMEI VARCHAR(255),
	 		USER_NAME VARCHAR(255),
	 		STATUS VARCHAR(255),
	 		EXTEND_PROP1 VARCHAR(255),
			EXTEND_PROP2 VARCHAR(255),
			CREATOR_ID BIGINT(20),
	 		CREATOR VARCHAR(255),
			CREATED_TIME DATETIME,
			LAST_OPERATOR_ID BIGINT(20),
	 		LAST_OPERATOR VARCHAR(255),
			LAST_OPERATED_TIME DATETIME,
			INDEX IDX_TMESSIMEI_IMEI(IMEI),
			INDEX IDX_TMESSIMEI_STUS(STATUS)			
		)ENGINE=INNODB  DEFAULT CHARSET=UTF8 DEFAULT COLLATE=UTF8_BIN;